<?php

namespace ripaym1970\autocrud\controllers;

use ripaym1970\autocrud\models\AdminModel;
use kartik\grid\EditableColumnAction;
use kartik\helpers\Html;
use ripaym1970\autocrud\components\actions\CacheFlushAction;
use ripaym1970\autocrud\components\actions\CallbackAction;
use ripaym1970\autocrud\components\actions\CreateAction;
use ripaym1970\autocrud\components\actions\DeleteAction;
use ripaym1970\autocrud\components\actions\DeleteImageAction;
use ripaym1970\autocrud\components\actions\ListAction;
use ripaym1970\autocrud\components\actions\MoveDownAction;
use ripaym1970\autocrud\components\actions\MoveImageDownAction;
use ripaym1970\autocrud\components\actions\MoveImageUpAction;
use ripaym1970\autocrud\components\actions\MoveUpAction;
use ripaym1970\autocrud\components\actions\NpDownloadAction;
use ripaym1970\autocrud\components\actions\PositionAction;
use ripaym1970\autocrud\components\actions\UpdateAction;
use ripaym1970\autocrud\components\actions\ViewAction;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii2mod\toggle\actions\ToggleAction;
use yii2tech\ar\search\ActiveSearchModel;

class CrudController extends \yii2tech\admin\CrudController
{
    public $modelClass = 'ripaym1970\autocrud\models\crud\{Table}Model';

    public $createScenario = 'create';

    public $table = ''; // Только для common/components/actions/CreateAction.php

    private $_table;

    private $_roles = ['editor', 'moderator', 'admin'];

    /**
     * @throws NotFoundHttpException
     */
    public function init()
    {
        parent::init();
        $this->_table = Yii::$app->request->get('table');
        $this->_table = $this->_table ?? Yii::$app->request->post('table');

        $issetTable = isset(Yii::$app->params['tables'][$this->_table]);
        if (!$issetTable) {
            throw new NotFoundHttpException('Table "' . $this->_table . '" not found');
        }

        $isCrud = Yii::$app->params['tables'][$this->_table]['crud_edit'] ?? true;
        //dd('$isCrud=',$isCrud);
        if (!$isCrud) {
            throw new NotFoundHttpException('Table "' . $this->_table . '" cannot be edited');
        }

        //$this->modelClass = 'ripaym1970\autocrud\models\crud\\' . Inflector::id2camel($table, '_') . 'Model';
        $this->modelClass = 'ripaym1970\autocrud\models\crud\\' . ucfirst($this->_table) . 'Model';
        $this->table = $this->_table;
        if (!empty(Yii::$app->params['tables'][$this->_table]['roles'])) {
            $this->_roles = Yii::$app->params['tables'][$this->_table]['roles'];
        }
    }

    public function beforeAction($action)
    {
        /** @var $identity AdminModel */
        $identity = Yii::$app->user->identity;
        //dd($identity->role, $this->_roles);
        if (!$identity || !in_array($identity->role, $this->_roles)) {
            throw new HttpException(404, 'У вас нет прав на просмотр этой страницы');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $parentActions = parent::actions();
        unset($parentActions['view']);
        $actions = ArrayHelper::merge(
            $parentActions,
            [
                'cache-flush'  => [
                    'class' => CacheFlushAction::class,
                ],
                'np-download'         => [
                    'class' => NpDownloadAction::class,
                ],
                'list'         => [
                    'class' => ListAction::class,
                ],
                'delete-image' => [
                    'class' => DeleteImageAction::class,
                ],
                'move-image-up'      => [
                    'class' => MoveImageUpAction::class,
                ],
                'move-image-down'    => [
                    'class' => MoveImageDownAction::class,
                ],
                'move-up'      => [
                    'class' => MoveUpAction::class,
                ],
                'move-down'    => [
                    'class' => MoveDownAction::class,
                ],
                'position'     => [
                    'class' => PositionAction::class,
                ],
                'delete'       => [
                    'class' => DeleteAction::class,
                ],
                'view'         => [
                    'class'        => ViewAction::class,
                ],
                'create'       => [
                    'class'    => CreateAction::class,
                    'scenario' => $this->createScenario,
                ],
                'update'       => [
                    'class'    => UpdateAction::class,
                    'scenario' => $this->updateScenario,
                ],
                'index'        => [
                    'newSearchModel' => function () {
                        $modelClass = $this->modelClass;
                        $tableName = $modelClass::tableName();
                        $query = $this->getQueryList($modelClass);

                        // Получим для сортировки поля модели
                        $columns = ArrayHelper::getValue(Yii::$app->params, 'tables.' . $tableName . '.columns', []);
                        $attributes = array_keys($columns);

                        // Получим связи
                        $tableRelations = ArrayHelper::getValue(Yii::$app->params, 'tables.' . $tableName . '.relations', []);
                        //dd('Получим связи $tableRelations=', $tableRelations);
                        $relations = prepareRelations($tableRelations);

                        $attributesTranslate = [];
                        // Если есть переводы
                        if (isset($relations['translations'])) {
                            // Получим для сортировки поля переводов
                            $attributesTranslate = array_keys(
                                ArrayHelper::getValue(
                                    Yii::$app->params,
                                    'tables.' . $modelClass::tableName() . '.behaviors.translations.variationAttributeDefaultValueMap',
                                    []
                                )
                            );
                            $attributes = array_merge($attributes, $attributesTranslate);
                        }
                        //dd($attributes);

                        return new ActiveSearchModel([
                            'model'               => $this->modelClass,
                            'dataProvider'        => [
                                'class'      => 'yii\data\ActiveDataProvider',
                                'pagination' => [
                                    'defaultPageSize' => 10,
                                    'pageSizeLimit'   => [10, 20, 50, 75, 100, 150, 200],
                                ],
                                'sort'       => [
                                    'attributes'   => $attributes,
                                    'defaultOrder' => ArrayHelper::getValue(
                                        Yii::$app->params,
                                        'tables.' . $modelClass::tableName() . '.defaultOrder',
                                        ['id' => SORT_DESC]
                                    ),
                                ],
                                'query'      => $query,
                            ],
                            // Тут не поля модели!
                            'attributes'          => [
                                'statusList' => [],
                                'roleList'   => [],
                            ],
                            'on afterCreateQuery' => function ($event) use ($modelClass, $relations, $attributes, $attributesTranslate) {
                                //dd($event);
                                //dd('Есть $relations=', $relations);exit();

                                // Если есть переводы
                                if (isset($relations['translations'])) {
                                    $trAlias = 'translate';
                                    $event->query->select[$modelClass::tableName() . '_id'] =
                                        $trAlias . '.' . $modelClass::tableName() . '_id';
                                    $event->query->select['language_id'] = $trAlias . '.language_id';

                                    // Добавим для поиска/фильтрации в $query поля переводов
                                    foreach ($attributesTranslate as $fieldName) {
                                        $event->query->select[$fieldName] = $trAlias . '.' . $fieldName;
                                    }

                                    // Приджойним таблицу с переводами
                                    $event->query->leftJoin(
                                        $modelClass::tableName() . '_translation AS ' . $trAlias,
                                        $trAlias . '.' . $relations['translations']['attribute'] . ' = self.id'
                                    );
                                    $event->query->groupBy('self.id');

                                    unset($relations['translations']);
                                    unset($relations['defaultTranslation']);
                                }
                                //dd('Есть $relations=', $relations);
                                //$zzz = $event->query;
                                //dd($zzz->prepare(\Yii::$app->db->queryBuilder)->createCommand()->rawSql);

                                if ($relations) {
                                    //dd('Есть необработанные $relations=', $relations);exit();

                                    $searchTypes = $event->sender->getSearchAttributeTypes();

                                    foreach ($relations as $relation => $relParams) {
                                        if ($relParams instanceof Closure) {
                                            continue;
                                        }
                                        //dd($relation, $relParams);

                                        //$key = $relParams['table'] . '_id';
                                        //$key = ($relParams['table'] ?? $relation) . '_id';
                                        //dd([$key, $searchTypes, $event->sender]);
                                        $key = $relParams['attribute'];

                                        // Если есть тип для поля и есть значение для поиска
                                        if (isset($searchTypes[$key]) && !empty($event->sender->{$key})) {
                                            // Если нет via-таблицы
                                            if (empty($relParams['via'])) {
                                                //$event->query->joinWith($relation);
                                                //dd($relParams);
                                                // Приджойним таблицу с переводами
                                                $event->query->leftJoin(
                                                    $relParams['table'] . ' AS ' . ($relParams['slug'] ?? $relParams['table']),
                                                    $relParams['table'] . '.id = self.' . $relParams['attribute']
                                                );
                                                //dd($event->query->prepare(Yii::$app->db->queryBuilder)->createCommand()->rawSql);
                                            } else {
                                                dd('Есть via-таблица=', $relParams['via']);
                                                //// Есть via-таблица
                                                //foreach ($relations as $relation1 => $relParams1) {
                                                //    if ($relParams1 instanceof Closure) {
                                                //        continue;
                                                //    }
                                                //    if ($relParams1['table'] === $relParams['via']) {
                                                //        // ? По идее должно быть связь, чтобы вызывать joinWith
                                                //        //$query = $this->hasMany($className, ['id' => $relation['table'] . '_id'])
                                                //        //    ->viaTable($relation['via'], [$relation['attribute'] => 'id']);
                                                //        //$event->query->joinWith($relation1);
                                                //        $event->query->leftJoin(
                                                //            $relation1,
                                                //            $relParams1['attribute'].' = self.id'
                                                //        );
                                                //    }
                                                //}
                                            }
                                        }
                                    }
                                }
                            },
                        ]);
                    },
                ],
                'edit' => [
                    'class' => EditableColumnAction::class,
                    'modelClass' => $this->modelClass,
                    'outputValue' => function (ActiveRecord $model, $attribute, $key, $index) {
                        $type = ArrayHelper::getValue(
                            Yii::$app->params,
                            'tables.' . $model->tableName() . '.columns.' . $attribute . '.type',
                            ''
                        );
                        if ($type == 'boolean' || $model->getTableSchema()->getColumn($attribute)->type == 'boolean') {
                            return Html::icon(
                                $model->$attribute ? 'check text-success' : 'times text-danger',
                                [],
                                'fa fa-'
                            );
                        }

                        return $model->$attribute;
                    },
                ],
                'toggle' => [
                    'class' => ToggleAction::class,
                    'modelClass' => $this->modelClass,
                    //// if you want to use flash messages
                    //'setFlash'     => true,
                    //'flashSuccess' => 'Success message',
                    //'flashError'   => 'Error message',
                    ///*'redirect'     => 'some-redirect-url',
                    // if you want to use custom code before saving the model
                    'preProcess' => function ($vars) {
                        if ($_REQUEST['attribute'] == 'default') {
                            $modelClass = $this->modelClass;
                            $modelClass::updateAll(['default' => 0,]);
                        }
                    },
                ],
            ]
        );

        $table = Yii::$app->request->get('table');
        $info = ArrayHelper::getValue(Yii::$app->params, 'tables.' . $table, []);
        foreach ($info as $key => $value) {
            // Если у таблицы есть actions
            if ($key === 'actions') {
                foreach ($value as $uKey => $action) {
                    $actions[$uKey] = [
                        'class'    => CallbackAction::class,
                        'callback' => $action,
                    ];
                }
            }
            // Если у таблицы есть список полей formFields
            if (strpos($key, 'formFields') === 0) {
                $uKey = strtolower(substr($key, 10) ?: 'update');
                //dd('$uKey=',$uKey);
                $actions[$uKey] = [
                    'class'    => UpdateAction::class,
                    'scenario' => $this->updateScenario,
                    'form'     => $uKey !== 'update' ? $uKey : '',
                ];
                //dd('$actions=',$uKey,$actions[$uKey]);
            }
        }

        return $actions;
    }

    /**
     * @param $modelClass
     *
     * @return ActiveQuery
     */
    public static function getQueryList($modelClass)
    {
        return $modelClass::find()
            ->alias('self')
            ->select([
                'self.*',
            ]);
    }
}
