// Generated by CoffeeScript 1.12.7
(function() {
  var AbstractForm,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  AbstractForm = (function(superClass) {
    extend(AbstractForm, superClass);

    function AbstractForm() {
      return AbstractForm.__super__.constructor.apply(this, arguments);
    }

    AbstractForm.prototype.ui = {
      'twitterTabs': '.nav-tabs li a',
      'errortab': '.tab-pane:has(.invalid-feedback:not(:empty)):first',
      'form': 'form:first',
      'reloadable': '.js-reload',
      'reloadableLink': 'a.js-reload'
    };

    AbstractForm.prototype.events = {
      'click .nav-tabs li a': 'twitterTabShow',
      'submit @ui.form': 'onFormSubmit',
      'change @ui.form': 'onFormChange',
      'change @ui.reloadable': 'onReloadableChange',
      'click @ui.reloadableLink': 'onReloadableChange',
      'reload': 'onReload'
    };

    AbstractForm.prototype.initialize = function(options) {
      AbstractForm.__super__.initialize.apply(this, arguments);
      this.id = options.id || null;
      this.templateData = options.templateData;
      this.listenTo(this, 'failure', this.onFailure);
      this.savingData = false;
      if (this.options.url) {
        this.loadContent();
      }
      if (this.templateData) {
        return this.render();
      }
    };

    AbstractForm.prototype.loadContent = function() {
      if (!this.options.url) {
        return;
      }
      progressOn($("body"));
      return $.get(this.options.url, (function(_this) {
        return function(data) {
          progressOff($("body"));
          if (!data.length) {
            return;
          }
          _this.templateData = data;
          return _this.render();
        };
      })(this));
    };

    AbstractForm.prototype.onFailure = function() {
      return this.render();
    };

    AbstractForm.prototype.finish = function() {
      var channel;
      this.trigger('success', this.id);
      channel = Backbone.Radio.channel("widget");
      channel.trigger("success", this, this.id);
      return this.destroy();
    };

    AbstractForm.prototype.cleanUp = function() {
      var base;
      if (typeof (base = this.ui.form).yiiActiveForm === "function") {
        base.yiiActiveForm('destroy');
      }
      return kendo.destroy(this.$el);
    };

    AbstractForm.prototype.onBeforeDestroy = function() {
      return this.cleanUp();
    };

    AbstractForm.prototype.onReload = function(e) {
      e.preventDefault();
      e.stopImmediatePropagation();
      if (this.ui.form.length) {
        this.onReloadableChange();
      }
      if (this.options.url) {
        return this.loadContent();
      }
    };

    AbstractForm.prototype.onFormSubmit = function(e) {
      var i, j, len, ref;
      e.preventDefault();
      e.stopImmediatePropagation();
      if (this.savingData) {
        return;
      }
      this.savingData = true;
      progressOn(this.$el);
      ref = this.$(".CodeMirror");
      for (j = 0, len = ref.length; j < len; j++) {
        i = ref[j];
        i.CodeMirror.toTextArea();
      }
      return this.ui.form.ajaxSubmit({
        forceSync: true,
        error: (function(_this) {
          return function() {
            progressOff(_this.$el);
            return _this.savingData = false;
          };
        })(this),
        success: (function(_this) {
          return function(data, status, xhr) {
            progressOff(_this.$el);
            _this.id = xhr.getResponseHeader("X-Model-ID") || _this.id;
            _this.savingData = false;
            if (!data || !data.length) {
              _this.finish();
              return;
            }
            _this.templateData = data;
            return _this.trigger('failure', _this.id);
          };
        })(this)
      });
    };

    AbstractForm.prototype.onBeforeRender = function() {
      return this.cleanUp();
    };

    AbstractForm.prototype.onYiiFormAfterValidate = function(event, messages, errorAttributes) {
      if (this.ui.twitterTabs.length && errorAttributes.length) {
        return this.selectTab($(errorAttributes[0].input).closest('.tab-pane'));
      }
    };

    AbstractForm.prototype.onRender = function() {
      var ref;
      progressOff(this.$el);
      this.ui.form.on('afterValidate', _.bind(this.onYiiFormAfterValidate, this));
      if ((ref = this.$('[data-toggle="tooltip"]')) != null) {
        ref.tooltip();
      }
      Backbone.Radio.channel("widget").trigger("render", this);
      if (!this.ui.form.length) {
        return;
      }
      if (this.ui.errortab.length) {
        return this.selectTab(this.ui.errortab);
      }
    };

    AbstractForm.prototype.selectTab = function($tabElement) {
      var id, link;
      id = $tabElement.prop('id');
      link = this.ui.twitterTabs.filter("[href=\"#" + id + "\"]:first");
      link.focus();
      return link.trigger('click');
    };

    AbstractForm.prototype.onReloadableChange = function() {
      var base, ref;
      application.addJsReload(this.ui.form);
      if ((ref = this.ui.form.data('yiiActiveForm')) != null) {
        ref.submitting = true;
      }
      if (typeof (base = this.ui.form).yiiActiveForm === "function") {
        base.yiiActiveForm('destroy');
      }
      return this.ui.form.submit();
    };

    AbstractForm.prototype.twitterTabShow = function(e) {
      var ref;
      e.preventDefault();
      return (ref = $(e.target)) != null ? ref.tab('show') : void 0;
    };

    AbstractForm.prototype.onFormChange = function() {};

    return AbstractForm;

  })(Marionette.View);

  application.Views.InlineForm = (function(superClass) {
    extend(InlineForm, superClass);

    function InlineForm() {
      return InlineForm.__super__.constructor.apply(this, arguments);
    }

    InlineForm.prototype.getTemplate = function() {
      if (!this.templateData) {
        return _.noop;
      }
      return _.template("" + this.templateData);
    };

    InlineForm.prototype.initialize = function() {
      InlineForm.__super__.initialize.apply(this, arguments);
      return this.header = null;
    };

    InlineForm.prototype.onFormChange = function() {
      var content, pane, title;
      pane = this.ui.form.closest(".tab-pane");
      this.header = pane.closest('.tab-content').parent().find("[href='#" + (pane.attr('id')) + "']");
      if (this.header.length && !$(".js-form-change-warning", this.header).length) {
        title = Yii.t("app", "Form has been changed, do not forget to save !");
        content = "<span class=\"js-form-change-warning badge bg-warning badge-icon cursor-pointer p-1 ml-1\" title=\"" + title + "\"> <i class=\"fas fa-exclamation-triangle\"></i> </span>";
        this.header.append(content);
      }
      return InlineForm.__super__.onFormChange.apply(this, arguments);
    };

    InlineForm.prototype.onFormSubmit = function() {
      var ref;
      if ((ref = this.header) != null) {
        ref.find('.js-form-change-warning').remove();
      }
      return InlineForm.__super__.onFormSubmit.apply(this, arguments);
    };

    return InlineForm;

  })(AbstractForm);

  application.Views.Form = (function(superClass) {
    extend(Form, superClass);

    function Form() {
      return Form.__super__.constructor.apply(this, arguments);
    }

    Form.prototype.defaultDialogOptions = function() {
      return {
        title: '',
        modal: true,
        width: '50vw',
        buttons: [],
        actions: [],
        autoOpen: true,
        minHeight: 150,
        minWidth: 350,
        position: {
          my: 'top',
          at: 'top+5%'
        },
        classes: {
          "ui-dialog": "ui-corner-all",
          "ui-dialog-titlebar": "ui-corner-all bg-primary-700 bg-success-gradient"
        },
        show: {
          effect: 'scale'
        },
        hide: {
          effect: 'scale'
        },
        open: (function(_this) {
          return function() {
            _this.dialogShown = true;
            if (_this.ui.errortab.length) {
              return _this.selectTab(_this.ui.errortab);
            }
          };
        })(this),
        close: (function(_this) {
          return function() {
            return _this.destroy();
          };
        })(this)
      };
    };

    Form.prototype.getTemplate = function() {
      if (!this.templateData) {
        return _.noop;
      }
      return _.template("<div class=\"popup-dialog\">" + this.templateData + "</div>");
    };

    Form.prototype.initialize = function(options1) {
      this.options = options1;
      this.dialogShown = false;
      this.options = $.extend(this.defaultDialogOptions(), this.options);
      this.configureButtons();
      return Form.__super__.initialize.apply(this, arguments);
    };

    Form.prototype.configureButtons = function() {
      var action, j, len, ref;
      ref = this.options.actions;
      for (j = 0, len = ref.length; j < len; j++) {
        action = ref[j];
        switch (action) {
          case 'save':
            this.options.buttons.push(this.saveButton());
            break;
          case 'ok':
            this.options.buttons.push(this.okButton());
            break;
          case 'remove':
            this.options.buttons.push(this.removeButton());
            break;
          case 'close':
            this.options.buttons.push(this.closeButton());
            break;
          default:
            this.options.buttons.push(action);
        }
      }
      return delete this.options.actions;
    };

    Form.prototype.onRender = function() {
      if (this.dialogShown) {
        this.$el.dialog('destroy');
        this.options.show = null;
        this.options.hide = null;
      }
      this.$el.dialog(this.options);
      return Form.__super__.onRender.apply(this, arguments);
    };

    Form.prototype.onBeforeDestroy = function() {
      Form.__super__.onBeforeDestroy.apply(this, arguments);
      if (this.dialogShown) {
        this.$el.dialog('destroy');
        return this.dialogShown = false;
      }
    };

    Form.prototype.okButton = function() {
      return {
        title: Yii.t('app', 'Ok'),
        text: Yii.t('app', 'Ok'),
        "class": 'btn btn-success',
        click: (function(_this) {
          return function() {
            if (!_this.ui.form.length) {
              _this.destroy();
              return;
            }
            return _this.ui.form.submit();
          };
        })(this)
      };
    };

    Form.prototype.saveButton = function() {
      return {
        title: Yii.t('app', 'Save'),
        text: Yii.t('app', 'Save'),
        "class": 'btn btn-success',
        click: (function(_this) {
          return function() {
            return _this.ui.form.submit();
          };
        })(this)
      };
    };

    Form.prototype.closeButton = function() {
      return {
        title: Yii.t('app', 'Close'),
        text: Yii.t('app', 'Close'),
        "class": 'btn btn-primary',
        click: (function(_this) {
          return function() {
            return _this.destroy();
          };
        })(this)
      };
    };

    Form.prototype.removeButton = function() {
      return {
        title: Yii.t('app', 'Remove'),
        text: Yii.t('app', 'Remove'),
        "class": 'btn btn-danger',
        click: (function(_this) {
          return function() {
            return _this.ui.form.submit();
          };
        })(this)
      };
    };

    return Form;

  })(AbstractForm);

  application.toggleObject = function(o) {
    return o.toggleClass('disabled js-disabled');
  };

  application.enableObject = function(o) {
    return o.removeClass('disabled js-disabled');
  };

  application.disableObject = function(o) {
    return o.addClass('disabled js-disabled');
  };

  application.confirmDialog = function(event, dialogOptions) {
    var defaultOptions;
    defaultOptions = {
      title: Yii.t("app", "Are you sure ?")
    };
    return bootbox.confirm(_.extend(defaultOptions, dialogOptions));
  };

  application.addJsReload = function($element) {
    return $element.append("<input type=\"hidden\" name=\"js-reload\" value=\"1\"/>");
  };

  $(function() {
    var actionSuccess, reloadDocument;
    $("body").on('click', '.js-disabled', function(e) {
      e.preventDefault();
      return e.stopImmediatePropagation();
    });
    reloadDocument = function() {
      progressOn($("body"));
      return location.reload();
    };
    $(document).on("reload", reloadDocument);
    actionSuccess = function() {
      progressOff($("body"));
      if (this.hasClass('js-reload-document')) {
        reloadDocument();
      }
      if (this.hasClass('js-reload-parent')) {
        return this.trigger('reload');
      }
    };
    $("body").on('click', '.js-destroy', function(e) {
      var params, target;
      e.preventDefault();
      target = $(this);
      params = target.data('params');
      return application.confirmDialog(e, {
        message: (params != null ? params.message : void 0) || Yii.t("app", "Are you sure you want to remove record ?"),
        title: (params != null ? params.title : void 0) || void 0,
        callback: function(result) {
          if (!result) {
            return;
          }
          return $.ajax({
            url: target.prop('href'),
            type: "DELETE",
            success: _.bind(actionSuccess, target)
          });
        }
      });
    });
    $("body").on('click', '.js-command', function(e) {
      var commandFunction, params, target;
      e.preventDefault();
      target = $(this);
      commandFunction = function() {
        progressOn($("body"));
        return $.post(target.prop('href'), {}, _.bind(actionSuccess, target));
      };
      params = target.data('params');
      if (!(params != null ? params['requires-confirmation'] : void 0)) {
        commandFunction.apply(e);
        return;
      }
      return application.confirmDialog(e, _.extend({
        callback: function(result) {
          if (!result) {
            return;
          }
          return commandFunction.apply(e);
        }
      }, params));
    });
    return $("body").on('click', '.js-dialog', function(e) {
      var button, buttons, form, klass, map, params, target;
      target = $(this);
      map = {
        'js-dialog-ok': 'ok',
        'js-dialog-save': 'save',
        'js-dialog-remove': 'remove',
        'js-dialog-close': 'close'
      };
      buttons = [];
      for (klass in map) {
        button = map[klass];
        if (target.hasClass(klass)) {
          buttons.push(button);
        }
      }
      params = target.data('params') || {};
      params.title = (params != null ? params.title : void 0) || target.prop('title') || '';
      params = _.extend(params, {
        url: target.prop('href'),
        actions: buttons
      });
      e.preventDefault();
      form = new application.Views.Form(params);
      return application.listenTo(form, 'success', function() {
        actionSuccess.call(target);
        return form.destroy();
      });
    });
  });

}).call(this);

//# sourceMappingURL=HtmlActions.js.map
